# Generated by Django 4.1.1 on 2022-12-15 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_alter_hesap_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesap',
            name='takipci',
            field=models.ManyToManyField(related_name='takipci', to=settings.AUTH_USER_MODEL),
        ),
    ]
