# Generated by Django 4.1.4 on 2022-12-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resim',
            field=models.FileField(blank=True, upload_to='postlar/'),
        ),
    ]
